name = "email"
main = "src/email.ts"
compatibility_date = "2023-06-28"

kv_namespaces = [
    { binding = "db", id = "f68f7a8b3b9e4c60aa8368023eac658a" }
]

r2_buckets = [
    { binding = "content", bucket_name = "emails-content" } 
]
